"""esquema inicial

Revision ID: 0001
Revises: 
Create Date: 2026-09-27 14:55:30.428098
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from app.modules.catalogo.seed import AREAS, ODS


revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actores',
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('tipo', sa.Enum('universidad', 'empresa', 'estado', 'comunidad', 'ong', name='tipoactor', native_enum=False), nullable=False),
    sa.Column('sector', sa.String(length=150), nullable=False),
    sa.Column('contacto', sa.String(length=200), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('creado_en', sa.Date(), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('areas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('ods',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('rol', sa.Enum('estudiante', 'docente', 'administrativo', 'aliado', 'admin', name='rol', native_enum=False), nullable=False),
    sa.Column('programa', sa.String(length=150), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('habilidades', sa.JSON(), nullable=False),
    sa.Column('intereses', sa.JSON(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('creado_en', sa.Date(), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_table('oportunidades',
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('entidad', sa.String(length=150), nullable=False),
    sa.Column('tipo', sa.Enum('convocatoria', 'financiacion', 'mentoria', 'infraestructura', name='tipooportunidad', native_enum=False), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('monto', sa.BigInteger(), nullable=True),
    sa.Column('cierra_en', sa.Date(), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('creado_por_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('creado_en', sa.Date(), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['creado_por_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_oportunidades_cierra_en'), 'oportunidades', ['cierra_en'], unique=False)
    op.create_index(op.f('ix_oportunidades_titulo'), 'oportunidades', ['titulo'], unique=False)
    op.create_table('proyectos',
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('resumen', sa.String(length=300), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('necesidades', sa.Text(), nullable=False),
    sa.Column('area_id', sa.Integer(), nullable=False),
    sa.Column('estado', sa.Enum('idea', 'formulacion', 'ejecucion', 'finalizado', 'pausado', name='estado', native_enum=False), nullable=False),
    sa.Column('avance', sa.SmallInteger(), nullable=False),
    sa.Column('presupuesto', sa.BigInteger(), nullable=False),
    sa.Column('lider', sa.String(length=150), nullable=False),
    sa.Column('equipo', sa.JSON(), nullable=False),
    sa.Column('etiquetas', sa.JSON(), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=True),
    sa.Column('creado_por_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('creado_en', sa.Date(), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('avance BETWEEN 0 AND 100', name='avance_rango'),
    sa.CheckConstraint('fecha_fin IS NULL OR fecha_fin >= fecha_inicio', name='fechas_coherentes'),
    sa.CheckConstraint('presupuesto >= 0', name='presupuesto_positivo'),
    sa.ForeignKeyConstraint(['area_id'], ['areas.id'], ),
    sa.ForeignKeyConstraint(['creado_por_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proyectos_area_id'), 'proyectos', ['area_id'], unique=False)
    op.create_index(op.f('ix_proyectos_creado_por_id'), 'proyectos', ['creado_por_id'], unique=False)
    op.create_index(op.f('ix_proyectos_estado'), 'proyectos', ['estado'], unique=False)
    op.create_index(op.f('ix_proyectos_titulo'), 'proyectos', ['titulo'], unique=False)
    op.create_table('oportunidad_areas',
    sa.Column('oportunidad_id', sa.Uuid(), nullable=False),
    sa.Column('area_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['areas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['oportunidad_id'], ['oportunidades.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('oportunidad_id', 'area_id')
    )
    op.create_table('oportunidad_ods',
    sa.Column('oportunidad_id', sa.Uuid(), nullable=False),
    sa.Column('ods_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ods_id'], ['ods.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['oportunidad_id'], ['oportunidades.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('oportunidad_id', 'ods_id')
    )
    op.create_table('proyecto_actores',
    sa.Column('proyecto_id', sa.Uuid(), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=False),
    sa.Column('rol', sa.String(length=60), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['actores.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['proyecto_id'], ['proyectos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('proyecto_id', 'actor_id')
    )
    op.create_table('proyecto_ods',
    sa.Column('proyecto_id', sa.Uuid(), nullable=False),
    sa.Column('ods_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ods_id'], ['ods.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['proyecto_id'], ['proyectos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('proyecto_id', 'ods_id')
    )
    # ### end Alembic commands ###

    # Datos iniciales del catálogo
    areas = sa.table("areas", sa.column("nombre", sa.String))
    ods = sa.table("ods", sa.column("id", sa.Integer), sa.column("nombre", sa.String))
    op.bulk_insert(areas, [{"nombre": n} for n in AREAS])
    op.bulk_insert(ods, [{"id": i, "nombre": n} for i, n in ODS])


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('proyecto_ods')
    op.drop_table('proyecto_actores')
    op.drop_table('oportunidad_ods')
    op.drop_table('oportunidad_areas')
    op.drop_index(op.f('ix_proyectos_titulo'), table_name='proyectos')
    op.drop_index(op.f('ix_proyectos_estado'), table_name='proyectos')
    op.drop_index(op.f('ix_proyectos_creado_por_id'), table_name='proyectos')
    op.drop_index(op.f('ix_proyectos_area_id'), table_name='proyectos')
    op.drop_table('proyectos')
    op.drop_index(op.f('ix_oportunidades_titulo'), table_name='oportunidades')
    op.drop_index(op.f('ix_oportunidades_cierra_en'), table_name='oportunidades')
    op.drop_table('oportunidades')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_table('ods')
    op.drop_table('areas')
    op.drop_table('actores')
    # ### end Alembic commands ###
